### PR TITLE
calculate diamond norm using dual problem

### LINKED ISSUE #53: diamond distance is not symmetric
Consider the following:
```
p=0.2
AD=KrausOperators([[1 0; 0 sqrt(p)], [0 sqrt(1-p); 0 0]])
AD2=KrausOperators([[1 0; 0 sqrt(2p)], [0 sqrt(1-2p); 0 0]])
println(diamond_distance(AD,AD2))
println(diamond_distance(AD2,AD))
```
The first line outputs ~0.17 while the second line outputs ~0.40.
This is a bug, since the diamond distance is symmetric

### PR DESCRIPTION
**Pull request by benkj**
This implements the same algorithm of [QETLAB](https://github.com/nathanieljohnston/QETLAB/blob/master/DiamondNorm.m), first discussed in [this](https://arxiv.org/pdf/1207.5726.pdf) paper, section 3

Fix #53

### CODE REVIEW

**Comment by benkj** [comment]
> Shouldn't it be simply `Z in :SDP` instead of `Z+Z' in :SDP`? Except fixing a bug, which I cannot reproduce, does the dual problem have advantages over the primal one? Better numerical performance?

I took inspiration from [qetlab](https://github.com/nathanieljohnston/QETLAB/blob/master/DiamondNorm.m) where they have the similar line 
```
       cons = [Y0,-Phi;-Phi',Y1];
        cons + cons' >= 0; % avoid some numerical problems: CVX often thinks things aren't symmetric without this
```
I also did notice some instability with just `Z in :SDP`. 

I was just playing with primal & dual formulation, and found that the dual one didn't have the buggy behaviour of #53 . Not sure if it has other advantages.

**Comment by benkj** [comment]
I agree that we should keep both versions. We should also force the correct `eps`. Why did you choose `eps=1e-7`?

**Comment by lpawela** [comment]
After some tests on this problem anything higher causes to hit `max_iters` limit. Also, I recall running into problems in other optimizations when `eps` was set to something smaller.

**Comment by benkj** [comment]
Ok. Does it make sense then do add `eps` as a parameter?
In case we can hit the `max_iter` with larger dimensional problems.

**Comment by lpawela** [comment]
Yes, the user should be able to set `eps` and `max_iters`.

**Comment by benkj** [comment]
In the new commit I added a test from #53 and implemented both the primal and dual problem with optional argument

**Comment by pgawron** [comment]
> I think we should keep both versions, `norm_diamond` should take an optional parameter like`dual=false` setting which approach is used.

We should have `method=:primal` as default with option for `method=:dual`. I believe it would be more Julianesque and elegant.

**Comment by benkj** [comment]
I'm implemented the 'julian' notation with `method=:primal` as default choice

**Pull request merged**
